{{ if eq .Values.redis.REDIS_INSTALL true  }}
apiVersion: v1
kind: Pod
metadata:
  name: redis-user
  labels:
    app: web2

spec:
  containers:
  - name: redis
    image: redis:5.0.4
    command:
      - redis-server
      - "/redis-master/redis.conf"
    env:
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6379
    resources:
      limits:
        cpu: "0.1"
    volumeMounts:
    - mountPath: /redis-master-data
      name: data
    - mountPath: /redis-master
      name: config
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: redis2-config
        items:
        - key: redis-config
          path: redis.conf
  nodeSelector:
    service: redis2

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis2-config
data:
  redis-config: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web2
  name: user-redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: web2
{{ end }}