---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.postgresql.POSTGRES_HOST | quote  }}
subsets:
- addresses:
  - ip: {{ .Values.postgresql.POSTGRES_IP }}
  ports:
  - port: {{ .Values.postgresql.POSTGRES_PORT }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.POSTGRES_HOST |quote  }}
spec:
  ports:
  - port: {{ .Values.postgresql.POSTGRES_PORT }}
    protocol: TCP
    targetPort: {{ .Values.postgresql.POSTGRES_PORT }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Values.containerSrv }}
spec:
  ports:
  - port: {{ .Values.containerPort }}
    protocol: TCP
    targetPort:  {{ .Values.containerPort }}
  selector:
    app: {{ .Release.Name }}
