apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: user
  name: userconfigmap

data:

  API_PREFIX: {{ .Values.postgresql.API_PREFIX | quote }}
  DATABASE: {{ .Values.postgresql.DATABASE | quote }}
  DB_ENTITIES: {{ .Values.postgresql.DB_ENTITIES | quote }}
  DB_HOST: {{ .Values.postgresql.DB_HOST | quote }}
  DB_MIGRATIONS: {{ .Values.postgresql.DB_MIGRATIONS | quote }}
  DB_PASSWORD: {{ .Values.postgresql.DB_PASSWORD | quote }}
  DB_PORT: {{ .Values.postgresql.DB_PORT | quote }}
  DB_TYPE: {{ .Values.postgresql.DB_TYPE | quote }}
  DB_USER: {{ .Values.postgresql.DB_USER | quote }}
  DEV_MODE: {{ .Values.postgresql.DEV_MODE | quote }}
  LOGGING: {{ .Values.postgresql.LOGGING | quote }}
  PORT: {{ .Values.containerPort | quote }}
  RABBIT_HOST: {{ .Values.rabbit.HOST | quote }} 
  RABBIT_PASS: {{ .Values.rabbit.RABBIT_PASS | quote }}
  RABBIT_PORT: {{ .Values.rabbit.RABBIT_PORT | quote }}
  RABBIT_URL: {{ .Values.rabbit.RABBIT_URL | quote }}
  RABBIT_USER: {{ .Values.rabbit.RABBIT_USER | quote }}
  REDIS_HOST: {{ .Values.redis.REDIS_HOST | quote }}
  REFRESH_TOKEN_TTL: {{ .Values.redis.REFRESH_TOKEN_TTL | quote }}
  SWAGGER_DESCRIPTION: {{ .Values.swager.SWAGGER_DESCRIPTION | quote }}
  SWAGGER_ENABLE: {{ .Values.swager.SWAGGER_ENABLE | quote }}
  SWAGGER_PREFIX: {{ .Values.swager.SWAGGER_PREFIX | quote }}
  SWAGGER_TITLE: {{ .Values.swager.SWAGGER_TITLE | quote }}

